### ISSUE TITLE
DDEP-0001:hypercore-header-for-manifestfeed

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-research#17]
## `@todo`
* [ ] write up first draft
* [ ] follow [DDEP-0000](https://github.com/playproject-io/datdot-research/issues/16)
* [ ] commit as `DDEP-0001:hypercore-header-for-manifestfeed.md`

---
**first draft** (work in progress)

also i have two more take aways from discussions and some thinking
1. we might want to use [DEP 0007 `dataStructureType`](https://github.com/datprotocol/DEPs/blob/master/proposals/0007-hypercore-header.md#usage-documentation) to identify if a given structure is one of a few supported types or a generic type
2. we might want to make up a convention using [DEP 0007 MyCustomHeader](https://github.com/datprotocol/DEPs/blob/master/proposals/0007-hypercore-header.md#reference-documentation) about what generic types are, where the main point would be to expect under `AdditionalData` an entry for `manifest` which points to a `feedkey` of the manifestfeed, which is probably a hypertrie to somehow store all the related feeds

**Comment by serapath** [comment]
# `first draft` (work in progress)

## context
**data structures on top of `hypercore`**
hypercore creates `feeds`  (a.k.a logs)
many `feeds` are not published via `hyperswarm` using their `discoveryKey`,
but instead are indirectly published via `hyperswarm` using the `discoveryKey` of a related `feed` (e.g. in `hyperdrive`, the `contentfeed` is published through the swarm of the related `metafeed` and it's `discoveryKey`)

### 1. hypercore
* creates the basic type of `feed`
* has only one main feed associated with a corresponding `"dat address"`
* by default is not aware of any related feeds it might reference via messages

### 2. hypertrie
* creates a special type of `feed`
* has only one main feed associated with a corresponding `"dat address"`
* by default is not aware of any related feeds it might reference via messages

### 3. hyperdrive
* creates special type of `feed`s
* has main `metafeed` associated with a corresponding `"dat address"`
  * in `message 0` references a related `contentfeed`
  * it otherwise is a **hypertrie**
    * which gives all related `feeds` via:
    * => `trie.list(‘mounts’, { hidden: true }, cb)`

### 4. kappacore
* creates the basic type of `feed`
* has only one main feed associated with a corresponding `"dat address"`
* by default is not aware of any related feeds it might reference via messages
* derives views from `log` and stores them in leveldb
  * e.g. sorted list of cabal messages per channel
    * => key: `channel!timestamp`, value: `feed@seq`
    * => leveldb range query pulls out channel msgs quickly for frontend

### 5. kappadb
...

### 6. cabal.chat
...

### ...
...

## problem
a `generic seeding service` receives a `"dat address"` and doesn't know which kind of data structure is behind that address and needs to know all related `hypercores` and how to retrieve them and a standard way of making them available to anyone who wants to use the data and data structure behind that "dat address"

## requirements
a `generic seeding service` should not need any data structure specific code to know how to seed the data. This means the seeding service should not need to know all currently existing data structures build on top of `hypercore` nor need to be updated for every such data structure created in the future.

## solution proposal
```
after reading through `mux.js`, It made me feel that `"manifest"`
might as well be a `manifestfeed` and the `manifest handshake`
could share the `manifest feedkey` so any peer online
could share it and eventually related feeds while the author is offline.
```

**Comment by martinheidegger** [comment]
To my understanding the reason as to why the hyperdrive structure is how it is relates to performance and memory use. Particularly important is the number of round-trips necessary to until a data structure can be explored. If we have to read the manifest data before we can connect to the feeds it is one entire initial roundtrip added, which can easily mean 200ms added delay. Having the url be the identifier on how the feeds are handled might make it a better best-practice. Maybe we could have "patterns" of feed identification. i.e. the hypertrie pattern of hyperdrive 10 or the cabal pattern, which is part of the url specification.

**Comment by serapath** [comment]
I answered here: https://github.com/datproject/comm-comm/issues/134#issuecomment-604806258

**Comment by RangerMauve** [comment]
I think it'd be cool if the related feeds mechanism was used just for cases when a peer doesn't know your data structure and wants to get related feeds for pinning and stuff, while keeping existing mechanisms that data structures use for performance.

Maybe related feeds is something you opt into loading after you get the initial data or through an extension that only certain peers will bother invoking?

**Comment by serapath** [comment]
@RangerMauve i hope this is fullfilled by the latest proposal update which i perceive to be:
https://github.com/datproject/comm-comm/issues/134#issuecomment-604808606

**Comment by serapath** [comment]
Otherwise - there is a "related" but maybe different problem, which is not about identifying the structure behind a certain DHT topic and/or hypercore (e.g. hypertrie, hyperdrive, cabal, etc...), because for it you don't even need any protocol handler at all when it comes to sharing a link.

But it's more about which (of the of course compatible) "apps" to use to open the content?
* is it a default app?
* is it a custom app?

Because it is hard to get new custom protocol handlers into browser, so you can instruct the browser which app to use to show content, i would recommend a different URL scheme, that allows more flexibility, because it only requires a single generic protocol handler for the entire ecosystem and url's would then look like:

**<protocol>://user:pass@subhandler`:host/path?params#fragment**

---
any thouhgts on that and whether that is part of this or a separate spec proposal?

**Comment by serapath** [comment]
additional considerations:
1. list not only identifiers of related feeds, but also include the latest known tree hash signatures. (e.g. web packages might need this feature to link to snapshots)

2.
