### ISSUE TITLE
app ideas

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-research#25]
## `@todo`
* [ ] mastodon backup
* [ ] webpages hosting (instead of github pages i.e.)
* [ ] reddit (communication by topics + in the future maybe even options to sell through the app)
* [ ] chat app
    - [ ] collect the best wireframe UX features from most popular mainstream chat apps (e.g. discord)
    - [ ] implement it as a static website
    - [ ] implement the UX features via hyper stack backed up to datdot one by one
* [ ] hackmd
* [ ] whitepaper generator (pandoc)
* [ ] iframe based browser
* [ ] wizardamigos
* [ ] dropbox
* [ ] data vizualization tool
* [ ] tools for scientist (sloan)
* [ ] winamp
* [ ] maker tools (ki-cad, js-cad...)
* [ ] images backup/publish tool (google photos, instagram)
* [ ] walkie talkie app (direct comm between people in natural disasters, protests etc., not to look like a chat, but rather real walkie talkie experience, bc folx understand that was p2p in some way)
---
