### ISSUE TITLE
refine datdot architecture

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-research#28]
## `@todo`
* [ ] compare with https://github.com/ipfs/specs/blob/master/KEYCHAIN.md
* [ ] compare vault/wallet with https://github.com/ipfs/specs/blob/master/KEYSTORE.md
* [ ] compare with https://github.com/ipfs/specs/blob/master/REPO.md
  * [ ] and https://github.com/ipfs/specs/blob/master/REPO_FS.md
* [ ] compare with https://github.com/ipfs/specs/blob/master/DWEB_ADDRESSING.md

---
