### ISSUE TITLE
2020.03.23-08:00amZ | consult with mafintosh

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-research#9]
## `@todo`
* [x] prepare all dat/hypercore/hyperswarm related questions for mafintosh
  * see: https://hackmd.io/MhHLTpNiT-yjgzsnLjkrvg?view
* [x] add some cryptography related questions about dat related crypto
* [x] schedule a meeting with @mafintosh

---
**output**
* [`datdot-research#17` DDEP-0001:hypercore-header-for-manifestfeed](https://github.com/playproject-io/datdot-research/issues/17)
**minutes**
* https://www.loom.com/share/116b9847d85b4d1ea06021a2c9d06bab
